clear all;
close all;
Fig=figure('Name','Autor',...
 'Units','normalized',...
 'NumberTitle','off','color',[0.9290, 0.6940, 0.1250]);

x=imread('autor.jpg'); 
image(x);
grid off;
axis off;


 
uicontrol('Style','pushbutton',...      
          'Units','normalized',...
          'Position',[0.17 0 0.7 0.08],...
          'String','INAPOI',...
          'backgroundcolor','g',...
          'FontName','Times New Roman',...
          'FontSize',16,...
          'Callback','close;start;');