clear all;
close all;
Fig=figure('Name','Schema circuit',...
 'Units','normalized',...
 'NumberTitle','off','color',[0.9290, 0.6940, 0.1250]);
y=imread('schema.png'); 
image(y);
grid off;
axis off;

 
uicontrol('Style','pushbutton',...      
          'Units','normalized',...
          'Position',[0.15 0.02 0.75 0.08],...
          'String','INAPOI',...
          'backgroundcolor','g',...
          'FontName','Times New Roman',...
          'FontSize',16,...
          'Callback','close;start;');