clear all;
close all;

Fig=figure('Name','Meniu',...
           'Units','normalized',...
           'Position',[0.1 0.1 0.8 0.8]);
       x=imread('poza4.jpeg');
                image(x);
                set(gca,'Position',[0 0 1 1]);
                
                
   Bt=uicontrol('Style','text',...
     'Units','normalized',...
     'Position',[0.13 0.9 0.7 0.1],...
     'backgroundcolor',[0.9290, 0.6940, 0.1250],...
     'FontName','Times New Roman',...
        'FontSize',50,...
     'foregroundcolor','black',...
     'String','Circuit RC de derivare'); 
 
                  
      Bbiblografie=uicontrol('Style','pushbutton',...         
                   'Units','normalized',...       
                   'Position',[0.1 0.8 0.1 0.1],...  
                   'backgroundcolor','y',...
                   'foregroundcolor','black',...
                   'String','Bibliografie',...
                   'FontName','Times New Roman',...
                   'FontSize',14,...
                   'Callback','bibliografie'); 
               
       Bpautor=uicontrol('Style','pushbutton',...         
                   'Units','normalized',...       
                   'Position',[0.1 0.1 0.1 0.1],... 
                   'backgroundcolor','y',...
                   'foregroundcolor','black',...
                   'String','Autor',... 
                   'FontName','Times New Roman',...
                   'FontSize',14,...
                   'Callback','autor'); 
               
        Bdocumentatie=uicontrol('Style','pushbutton',...         
                   'Units','normalized',...       
                   'Position',[0.8 0.8 0.1 0.1],... 
                   'backgroundcolor','y',...
                   'foregroundcolor','black',...
                   'String','Teorie',...  
                   'FontName','Times New Roman',...
                   'FontSize',14,...
                   'Callback','teorie'); 
               
         BpCIRCUIT=uicontrol('Style','pushbutton',...         
                   'Units','normalized',...       
                   'Position',[0.8 0.1 0.1 0.1],...  
                   'backgroundcolor','y',...
                   'foregroundcolor','black',...
                   'String','Schema',...   
                   'FontName','Times New Roman',...
                   'FontSize',14,...
                   'Callback','schema'); 
         
        B2=uicontrol('Style','Pushbutton',...
                   'Units','normalized',...
                   'String','Grafice',...
                   'Position',[0.4 0.45 0.15 0.1],...
                   'backgroundcolor','y',...
                   'foregroundcolor','black',...
                   'FontName','Times New Roman',...
                   'FontSize',14,...
                   'Callback', 'start_proiect' );
        
        Bc=uicontrol('Style','pushbutton',...              
                   'Units','normalized',...       
                   'Position',[0.45 0.0 0.08 .05],...  
                   'backgroundcolor','g',...
                   'foregroundcolor','black',...
                   'string','IESIRE',... 
                   'FontName','Times New Roman',...
                   'FontSize',16,...
                   'Callback','close');
               

